ALTER TABLE `results`
  RENAME COLUMN `Submission ID` TO `submission_id`,
  RENAME COLUMN `What is your age?` TO `age`,
  RENAME COLUMN `How many cups of coffee do you typically drink per day?` TO `daily_coffee_cups`,
  RENAME COLUMN `Where do you typically drink coffee?` TO `coffee_drink_location`,
  RENAME COLUMN `Where do you typically drink coffee? (At home)` TO `coffee_drink_location_home`,
  RENAME COLUMN `Where do you typically drink coffee? (At the office)` TO `coffee_drink_location_office`,
  RENAME COLUMN `Where do you typically drink coffee? (On the go)` TO `coffee_drink_location_on_the_go`,
  RENAME COLUMN `Where do you typically drink coffee? (At a cafe)` TO `coffee_drink_location_cafe`,
  RENAME COLUMN `Where do you typically drink coffee? (None of these)` TO `coffee_drink_location_none`,
  RENAME COLUMN `How do you brew coffee at home?` TO `home_brew_method`,
  RENAME COLUMN `How do you brew coffee at home? (Pour over)` TO `home_brew_pour_over`,
  RENAME COLUMN `How do you brew coffee at home? (French press)` TO `home_brew_french_press`,
  RENAME COLUMN `How do you brew coffee at home? (Espresso)` TO `home_brew_espresso`,
  RENAME COLUMN `How do you brew coffee at home? (Coffee brewing machine)` TO `home_brew_machine`,
  RENAME COLUMN `How do you brew coffee at home? (Pod/capsule machine)` TO `home_brew_pod`,
  RENAME COLUMN `How do you brew coffee at home? (Instant coffee)` TO `home_brew_instant`,
  RENAME COLUMN `How do you brew coffee at home? (Bean-to-cup machine)` TO `home_brew_bean_to_cup`,
  RENAME COLUMN `How do you brew coffee at home? (Cold brew)` TO `home_brew_cold_brew`,
  RENAME COLUMN `How do you brew coffee at home? (Coffee extract (e.g. Cometeer))` TO `home_brew_extract`,
  RENAME COLUMN `How do you brew coffee at home? (Other)` TO `home_brew_other`,
  RENAME COLUMN `How else do you brew coffee at home?` TO `additional_home_brew_methods`,
  RENAME COLUMN `On the go, where do you typically purchase coffee?` TO `purchase_location_on_the_go`,
  RENAME COLUMN `On the go,... purchase coffee? (National chain)` TO `purchase_location_national_chain`,
  RENAME COLUMN `On the go, ... purchase coffee? (Local cafe)` TO `purchase_location_local_cafe`,
  RENAME COLUMN `On the go, ... purchase coffee? (Drive-thru)` TO `purchase_location_drive_thru`,
  RENAME COLUMN `On the go, ... purchase coffee? (Specialty coffee shop)` TO `purchase_location_specialty_shop`,
  RENAME COLUMN `On the go, ... purchase coffee? (Deli or supermarket)` TO `purchase_location_deli_supermarket`,
  RENAME COLUMN `On the go, ... purchase coffee? (Other)` TO `purchase_location_other`,
  RENAME COLUMN `Where else do you purchase coffee?` TO `additional_purchase_locations`,
  RENAME COLUMN `What is your favorite coffee drink?` TO `favorite_coffee_drink`,
  RENAME COLUMN `Please specify what your favorite coffee drink is` TO `favorite_drink_specify`,
  RENAME COLUMN `Do you usually add anything to your coffee?` TO `additions_to_coffee`,
  RENAME COLUMN `Do you usually ... coffee? (No - just black)` TO `add_black`,
  RENAME COLUMN `Do ... coffee? (Milk, dairy alternative, or coffee creamer)` TO `add_milk`,
  RENAME COLUMN `Do you usually ... coffee? (Sugar or sweetener)` TO `add_sugar`,
  RENAME COLUMN `Do you usually ... coffee? (Flavor syrup)` TO `add_flavor_syrup`,
  RENAME COLUMN `Do you usually ... coffee? (Other)` TO `add_other`,
  RENAME COLUMN `What else do you add to your coffee?` TO `additional_additions`,
  RENAME COLUMN `What kind of dairy do you add?` TO `dairy_type`,
  RENAME COLUMN `What kind of dairy do you add? (Whole milk)` TO `dairy_whole_milk`,
  RENAME COLUMN `What kind of dairy do you add? (Skim milk)` TO `dairy_skim_milk`,
  RENAME COLUMN `What kind of dairy do you add? (Half and half)` TO `dairy_half_and_half`,
  RENAME COLUMN `What kind of dairy do you add? (Coffee creamer)` TO `dairy_creamer`,
  RENAME COLUMN `What kind of dairy do you add? (Flavored coffee creamer)` TO `dairy_flavored_creamer`,
  RENAME COLUMN `What kind of dairy do you add? (Oat milk)` TO `dairy_oat_milk`,
  RENAME COLUMN `What kind of dairy do you add? (Almond milk)` TO `dairy_almond_milk`,
  RENAME COLUMN `What kind of dairy do you add? (Soy milk)` TO `dairy_soy_milk`,
  RENAME COLUMN `What kind of dairy do you add? (Other)` TO `dairy_other`,
  RENAME COLUMN `What kind of sugar or sweetener do you add?` TO `sweetener_type`,
  RENAME COLUMN `What ... sweetener do you add? (Granulated Sugar)` TO `sweetener_granulated_sugar`,
  RENAME COLUMN `What ... sweetener do you add? (Artificial Sweeteners)` TO `sweetener_artificial`,
  RENAME COLUMN `What ... sweetener do you add? (Honey)` TO `sweetener_honey`,
  RENAME COLUMN `What ... sweetener do you add? (Maple Syrup)` TO `sweetener_maple_syrup`,
  RENAME COLUMN `What ... sweetener do you add? (Stevia)` TO `sweetener_stevia`,
  RENAME COLUMN `What ... sweetener do you add? (Agave Nectar)` TO `sweetener_agave`,
  RENAME COLUMN `What ... sweetener do you add? (Brown Sugar)` TO `sweetener_brown_sugar`,
  RENAME COLUMN `What ... sweetener do you add? (Raw Sugar (Turbinado))` TO `sweetener_raw_sugar`,
  RENAME COLUMN `What kind of flavorings do you add?` TO `flavoring_type`,
  RENAME COLUMN `What kind of flavorings do you add? (Vanilla Syrup)` TO `flavoring_vanilla`,
  RENAME COLUMN `What kind of flavorings do you add? (Caramel Syrup)` TO `flavoring_caramel`,
  RENAME COLUMN `What kind of flavorings do you add? (Hazelnut Syrup)` TO `flavoring_hazelnut`,
  RENAME COLUMN `What kind of flavorings do you add? (Cinnamon (Ground or Stick))` TO `flavoring_cinnamon`,
  RENAME COLUMN `What kind of flavorings do you add? (Peppermint Syrup)` TO `flavoring_peppermint`,
  RENAME COLUMN `What kind of flavorings do you add? (Other)` TO `flavoring_other`,
  RENAME COLUMN `What other flavoring do you use?` TO `additional_flavorings`,
  RENAME COLUMN `Before ... best described what kind of coffee you like?` TO `coffee_preference_description`,
  RENAME COLUMN `How strong do you like your coffee?` TO `coffee_strength`,
  RENAME COLUMN `What roast level of coffee do you prefer?` TO `coffee_roast_preference`,
  RENAME COLUMN `How much caffeine do you like in your coffee?` TO `caffeine_preference`,
  RENAME COLUMN `Lastly, how would you rate your own coffee expertise?` TO `self_rated_expertise`,
  RENAME COLUMN `Coffee A - Bitterness` TO `coffee_a_bitterness`,
  RENAME COLUMN `Coffee A - Acidity` TO `coffee_a_acidity`,
  RENAME COLUMN `Coffee A - Personal Preference` TO `coffee_a_preference`,
  RENAME COLUMN `Coffee A - Notes` TO `coffee_a_notes`,
  RENAME COLUMN `Coffee B - Bitterness` TO `coffee_b_bitterness`,
  RENAME COLUMN `Coffee B - Acidity` TO `coffee_b_acidity`,
  RENAME COLUMN `Coffee B - Personal Preference` TO `coffee_b_preference`,
  RENAME COLUMN `Coffee B - Notes` TO `coffee_b_notes`,
  RENAME COLUMN `Coffee C - Bitterness` TO `coffee_c_bitterness`,
  RENAME COLUMN `Coffee C - Acidity` TO `coffee_c_acidity`,
  RENAME COLUMN `Coffee C - Personal Preference` TO `coffee_c_preference`,
  RENAME COLUMN `Coffee C - Notes` TO `coffee_c_notes`,
  RENAME COLUMN `Coffee D - Bitterness` TO `coffee_d_bitterness`,
  RENAME COLUMN `Coffee D - Acidity` TO `coffee_d_acidity`,
  RENAME COLUMN `Coffee D - Personal Preference` TO `coffee_d_preference`,
  RENAME COLUMN `Coffee D - Notes` TO `coffee_d_notes`,
  RENAME COLUMN `Between Coffee A, Coffee B, and Coffee C which did you prefer?` TO `preferred_coffee_abc`,
  RENAME COLUMN `Between Coffee A and Coffee D, which did you prefer?` TO `preferred_coffee_ad`,
  RENAME COLUMN `Lastly, what was your favorite overall coffee?` TO `favorite_overall_coffee`,
  RENAME COLUMN `Do you work from home or in person?` TO `work_location`,
  RENAME COLUMN `In total, much money ... coffee in a month?` TO `monthly_coffee_spending`,
  RENAME COLUMN `Why do you drink coffee?` TO `reason_for_drinking_coffee`,
  RENAME COLUMN `Why do you drink coffee? (It tastes good)` TO `reason_tastes_good`,
  RENAME COLUMN `Why do you drink coffee? (I need the caffeine)` TO `reason_caffeine`,
  RENAME COLUMN `Why do you drink coffee? (I need the ritual)` TO `reason_ritual`,
  RENAME COLUMN `Why do you drink coffee? (It makes me go to the bathroom)` TO `reason_bathroom`,
  RENAME COLUMN `Why do you drink coffee? (Other)` TO `reason_other`,
  RENAME COLUMN `Other reason for drinking coffee` TO `additional_reasons`,
  RENAME COLUMN `Do you like the taste of coffee?` TO `likes_coffee_taste`,
  RENAME COLUMN `Do you know where your coffee comes from?` TO `knows_coffee_origin`,
  RENAME COLUMN `What is the most you've ever paid for a cup of coffee?` TO `max_paid_for_coffee`,
  RENAME COLUMN `What is the most willing to pay for a cup?` TO `willing_to_pay_for_coffee`,
  RENAME COLUMN `Do you feel like good value when buy coffee at a cafe?` TO `perceived_value_cafe`,
  RENAME COLUMN `Approximately how much spent on coffee equipment past 5 years?` TO `coffee_equipment_spending`,
  RENAME COLUMN `Do you feel like getting good value your coffee equipment?` TO `perceived_value_equipment`,
  RENAME COLUMN `Gender` TO `gender`,
  RENAME COLUMN `Gender (please specify)` TO `gender_specify`,
  RENAME COLUMN `Education Level` TO `education_level`,
  RENAME COLUMN `Ethnicity/Race` TO `ethnicity`,
  RENAME COLUMN `Ethnicity/Race (please specify)` TO `ethnicity_specify`,
  RENAME COLUMN `Employment Status` TO `employment_status`,
  RENAME COLUMN `Number of Children` TO `number_of_children`,
  RENAME COLUMN `Political Affiliation` TO `political_affiliation`;